export const service = [
  {
    _id: 1,
    name: "cleaning",
  },
  {
    _id: 2,
    name: "cooking",
  },
  {
    _id: 3,
    name: "gardening",
  },
];

export const price = [
  {
    _id: 1,
    name: "Any",
    array: [],
  },
  {
    _id: 2,
    name: "$0 to $299",
    array: [0, 299],
  },
  {
    _id: 3,
    name: "$300 to $599",
    array: [300, 599],
  },
  {
    _id: 4,
    name: "$600 to $999",
    array: [600, 999],
  },
  {
    _id: 5,
    name: "$1000 to $1999",
    array: [1000, 1999],
  },
  {
    _id: 6,
    name: "More than 2000$",
    array: [2000, 1500000],
  },
];

export const ratings = [
  { label: "0", value: 0 },
  { label: "1", value: 1 },
  { label: "2", value: 2 },
  { label: "3", value: 3 },
  { label: "4", value: 4 },
  { label: "5", value: 5 },
  { label: "6", value: 6 },
  { label: "7", value: 7 },
  { label: "8", value: 8 },
  { label: "9", value: 9 },
  { label: "10", value: 10 },
];

export const week = [
  {
    _id: 1,
    name: "Monday",
  },
  {
    _id: 2,
    name: "Tuesday",
  },
  {
    _id: 3,
    name: "Wednesday",
  },
  {
    _id: 4,
    name: "Thursday",
  },
  {
    _id: 5,
    name: "Friday",
  },
  {
    _id: 6,
    name: "Saturday",
  },
  {
    _id: 7,
    name: "Sunday",
  },
];

export const areas = [
  {
    _id: 1,
    label: "Tunis",
    lat: 36.8008,
    lon: 10.18,
    delegations: [
      "Bab Bhar",
      "Bab Souika",
      "Bardo",
      "Bouhaira",
      "Carthage",
      "El Khadra",
      "El Menzah",
      "El Ouardia",
      "El Tahrir",
      "Ezzouhour",
      "Hrairia",
      "Jebel Jelloud",
      "Kabaria",
      "La Goulette",
      "La Marsa",
      "Le Kram",
      "Medina",
      "Omrane",
      "Omrane Superieur",
      "Sidi El Bechir",
      "Sidi Hassine",
      "Sijoumi",
    ],
  },
  {
    _id: 2,
    label: "Sfax",
    lat: 34.75,
    lon: 10.72,
    delegations: [
      "Agareb",
      "Bir Ali Ben Khelifa",
      "El Amra",
      "El Ghraiba",
      "Hencha",
      "Jebeniana",
      "Kerkennah",
      "Mahres",
      "Menzel Chaker",
      "Sakiet Eddaier",
      "Sakiet Ezzit",
      "Sfax Medina",
      "Sfax West",
      "Sfax South",
      "Skhira",
      "Thyna",
    ],
  },
  {
    _id: 3,
    label: "Sousse",
    lat: 35.83,
    lon: 10.625,
    delegations: [
      "Akouda",
      "Bouficha",
      "Enfidha",
      "Hammam Sousse",
      "Hergla",
      "Kalaa Kebira",
      "Kalaa Sghira",
      "Kondar",
      "M'Saken",
      "Sidi Bou Ali",
      "Sidi El Heni",
      "Sousse Jaouhara",
      "Sousse Medina",
      "Sousse Riadh",
      "Sousse Sidi Abdelhamid",
      "Zaouia Ksiba Thrayat",
    ],
  },
  {
    _id: 4,
    label: "Gabès",
    lat: 33.9004,
    lon: 10.1,
    delegations: [
      "Gabes Medina",
      "Gabes West",
      "Gabes South",
      "Ghannouch",
      "Hamma",
      "Mareth",
      "Matmata",
      "New Matmata",
      "Menzel Habib",
      "Metouia",
    ],
  },
  {
    _id: 5,
    label: "Kairouan",
    lat: 35.6804,
    lon: 10.1,
    delegations: [
      "Alaa",
      "Bouhajla",
      "Chebika",
      "Chrarda",
      "Haffouz",
      "Hajeb El Ayoun",
      "Kairouan North",
      "Kairouan South",
      "Nasrallah",
      "Oueslatia",
      "Sbikha",
    ],
  },
  {
    _id: 6,
    label: "Bizerte",
    lat: 37.2904,
    lon: 9.855,
    delegations: [
      "Bizerte North",
      "Bizerte South",
      "Djoumime",
      "El Alia",
      "Ghar El Melh",
      "Ghezala",
      "Mateur",
      "Menzel Bourguiba",
      "Menzel Jemil",
      "Ras Jebel",
      "Sejenane",
      "Tinja",
      "Utique",
      "Zarzouna",
    ],
  },
  {
    _id: 7,
    label: "Gafsa",
    lat: 34.4204,
    lon: 8.78,
    delegations: [
      "Belkhir",
      "Gafsa North",
      "Gafsa South",
      "Guetar",
      "Ksar",
      "Mdhilla",
      "Metlaoui",
      "Oum Larais",
      "Redeyef",
      "Sened",
      "Sidi Aich",
    ],
  },
  {
    _id: 8,
    label: "Nabeul",
    lat: 36.4603,
    lon: 10.73,
    delegations: [
      "Beni Khalled",
      "Beni Khiar",
      "Bou Argoub",
      "Dar Chaabane El Fehri",
      "El Mida",
      "Grombalia",
      "Hammam Ghezaz",
      "Hammamet",
      "Haouaria",
      "Kelibia",
      "Korba",
      "Menzel Bouzelfa",
      "Menzel Temime",
      "Nabeul",
      "Soliman",
      "Takelsa",
    ],
  },
  {
    _id: 9,
    label: "Ariana",
    lat: 36.8667,
    lon: 10.2,
    delegations: [
      "Ariana",
      "Medina",
      "Ettadhamen",
      "Kalaat El Andalous",
      "Mnihla",
      "Raoued",
      "Sidi Thabet",
      "Soukra",
    ],
  },
  {
    _id: 10,
    label: "Kasserine",
    lat: 35.1804,
    lon: 8.83,
    delegations: [
      "Ayoun",
      "Ezzouhour",
      "Feriana",
      "Foussana",
      "Hassi El Ferid",
      "Hidra",
      "Jedeliane",
      "Kasserine North",
      "Kasserine South",
      "Majel Belabbes",
      "Sbeitla",
      "Sbiba",
      "Thala",
    ],
  },
  {
    _id: 11,
    label: "Monastir",
    lat: 35.7307,
    lon: 10.7673,
    delegations: [
      "Bekalta",
      "Bembla",
      "Beni Hassen",
      "Jammel",
      "Ksar Hellal",
      "Ksibet El Mediouni",
      "Moknine",
      "Monastir",
      "Ouerdanine",
      "Sahline",
      "Sayada-Lamta-Bou Hjar",
      "Teboulba",
      "Zeramdine",
    ],
  },
  {
    _id: 12,
    label: "Tataouine",
    lat: 33.0,
    lon: 10.4667,
    delegations: [
      "Bir Lahmar",
      "Dhiba",
      "Ghomrassen",
      "Remada",
      "Samar",
      "Tataouine North",
      "Tataouine South",
    ],
  },
  {
    _id: 13,
    label: "Medenine",
    lat: 33.4,
    lon: 10.4167,
    delegations: [
      "Ben Gardane",
      "Beni Khedache",
      "Djerba Ajim",
      "Djerba Midoun",
      "Djerba Houmt Souk",
      "Medenine North",
      "Medenine South",
      "Sidi Makhlouf",
      "Zarzis",
    ],
  },
  {
    _id: 14,
    label: "Béja",
    lat: 36.7304,
    lon: 9.19,
    delegations: [
      "Amdoun",
      "Beja North",
      "Beja South",
      "Goubellat",
      "Mejez El Bab",
      "Nefza",
      "Teboursouk",
      "Testour",
      "Thibar",
    ],
  },
  {
    _id: 15,
    label: "Jendouba",
    lat: 36.5,
    lon: 8.75,
    delegations: [
      "Aïn Draham",
      "Balta",
      "Bousalem",
      "Fernana",
      "Ghardimaou",
      "Jendouba",
      "Jendouba Nord",
      "Oued Mliz",
      "Tabarka",
    ],
  },
  {
    _id: 16,
    label: "El Kef",
    lat: 36.1826,
    lon: 8.7148,
    delegations: [
      "Dahmani",
      "Es Sers",
      "Jerissa",
      "Kalaa Khasbat",
      "Kalaat Senane",
      "Kef East",
      "Kef West",
      "Ksour",
      "Nebeur",
      "Sakiet Sidi Youssef",
      "Tajerouine",
    ],
  },
  {
    _id: 17,
    label: "Mahdia",
    lat: 35.4839,
    lon: 11.0409,
    delegations: [
      "Borj El Amri",
      "Douar Hicher",
      "El Battan",
      "Jedaida",
      "Manouba",
      "Mornaguia",
      "Oued Ellil",
      "Tebourba",
    ],
  },
  {
    _id: 18,
    label: "Sidi Bouzid",

    lat: 35.0167,
    lon: 9.5,
    delegations: [
      "Bir El Hfay",
      "Jelma",
      "Mazzouna",
      "Meknassi",
      "Menzel Bouzaiene",
      "Ouled Haffouz",
      "Regueb",
      "Sabalat Ouled Asker",
      "Sidi Ali Ben Aoun",
      "Sidi Bouzid East",
      "Sidi Bouzid West",
      "Souk Jedid",
    ],
  },
  {
    _id: 19,
    label: "Tozeur",
    lat: 33.9304,
    lon: 8.13,
    delegations: [
      "Degueche (Degache)",
      "Hazoua",
      "Nefta",
      "Tamaghza",
      "Tozeur",
    ],
  },
  {
    _id: 20,
    label: "Siliana",
    lat: 36.0833,
    lon: 9.3833,
    delegations: [
      "Bargou",
      "Bouarada",
      "El Aroussa",
      "El Krib",
      "Gaafour",
      "Kesra",
      "Makthar",
      "Rouhia",
      "Sidi Bourouis",
      "Siliana North",
      "Siliana South",
    ],
  },
  {
    _id: 21,
    label: "Kebili",
    lat: 33.69,
    lon: 8.971,
    delegations: [
      "Douz North",
      "Douz South",
      "Faouar",
      "Kebili North",
      "Kebili South",
      "Souk El Ahed",
    ],
  },
  {
    _id: 22,
    label: "Zaghouan",
    lat: 36.4,
    lon: 10.147,
    delegations: [
      "Bir Mchergua",
      "Fahs",
      "Nadhour",
      "Saouaf",
      "Zaghouan",
      "Zriba",
    ],
  },
  {
    _id: 23,
    label: "Ben Arous",
    lat: 36.7545,
    lon: 10.2217,
    delegations: [
      "Ben Arous",
      "Boumhel",
      "El Mourouj",
      "Ezzahra",
      "Fouchana",
      "Hammam Chott",
      "Hammam Lif",
      "M'Hamdia",
      "Medina Jedida",
      "Megrine",
      "Mornag",
      "Rades",
    ],
  },
  {
    _id: 24,
    label: "Manouba",
    lat: 36.8101,
    lon: 10.0956,
    delegations: [
      "Borj El Amri",
      "Douar Hicher",
      "El Battan",
      "Jedaida",
      "Manouba",
      "Mornaguia",
      "Oued Ellil",
      "Tebourba",
    ],
  },
];
